apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-web-ui
  namespace: longhorn-system
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host(`longhorn.kube.ancored.ru`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80