kube-controller-manager-arg: bind-address=0.0.0.0
kube-proxy-arg: metrics-bind-address=0.0.0.0
kube-scheduler-arg: bind-address=0.0.0.0
etcd-expose-metrics: true
kubelet-arg: containerd=/run/k3s/containerd/containerd.sock