apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-test