deployment:
  replicas: 3
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [web, websecure]
    matchRule: Host(`traefik.kube.ancored.ru`)
gateway:
  namespacePolicy: All
providers:
  kubernetesCRD:
    allowCrossNamespace: true