apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-istio
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        # Custom log format that includes all headers
        log_format headers '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          '"canary: $http_x_canary" '
                          '"x-canary: $http_x_canary" '
                          '"all_headers: $http_host|$http_x_forwarded_for|$http_x_forwarded_proto"';
        
        # Enable access logging with headers
        access_log /var/log/nginx/access.log headers;
        error_log  /var/log/nginx/error.log debug;
        
        sendfile        on;
        keepalive_timeout  65;
        
        server {
            listen       80;
            server_name  localhost;
            
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            
            # Debug endpoint to show all headers
            location /debug-headers {
                return 200 "Headers received:\nCanary: $http_canary\nHost: $http_host\nUser-Agent: $http_user_agent\nX-Forwarded-For: $http_x_forwarded_for\nX-Forwarded-Proto: $http_x_forwarded_proto\n";
                add_header Content-Type text/plain;
            }
        }
    }