services:
  postgres:
    image: postgres:17
    ports:
      - 5467:5432
    restart: always
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vault
      POSTGRES_DB: vault
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vault"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    restart: always
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_API_ADDR: 'http://0.0.0.0:8200'
    volumes:
      - vault_data:/vault/data
      - ./vault.hcl:/vault/config/vault.hcl:ro # Mount your Vault configuration file
    entrypoint: >
      vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK # Required to lock memory for security
    depends_on:
      - postgres

volumes:
  vault_data: